[build]
  command = "npm run build"
  functions = "src/functions"
  publish = "_site"

# ---------------------------------------------------------------------------- #
# Build plugins                                                                #
# ---------------------------------------------------------------------------- #

# https://github.com/MarcelloTheArcane/netlify-plugin-csp-generator
[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "_site"
  reportOnly = false
  reportTo = "default"
  reportURI = "https://giacomodebidda.report-uri.com"

  # childSrc
  # This is a fallback for frame-src and worker-src. I keep it for backward
  # compatibility. Both 'child-src' and 'frame-src' should exist in order to
  # protect Clickjacking, Formjacking, Data Exfiltration and more.

  # connectSrc
  # I need to fetch images from Cloudinary and to POST analytics to Plausible.

  # fontSrc
  # Allow only font files hosted on this origin (self-hosted).

  # frameSrc
  # Allow iframes from YouTube, Vimeo.

  # imgSrc
  # Allow images hosted on this origin and on my Cloudinary media library.

  # reportURI
  # Send CSP violations to reporting service
  # Note: report-uri is a deprecated CSP directive, but I include it here
  # because Firefox does not yet support the report-to CSP directive, nor the
  # Report-To header.

  # scriptSrc
  # Unfortunately Firefox does not yet support the script-src-attr and
  # script-src-elem CSP directives, so we need to fallback to script-src
  # https://bugzilla.mozilla.org/show_bug.cgi?id=1529337
  # 'unsafe-inline' is to be backward compatible with older browsers. It's
  # ignored by browsers supporting nonces/hashes.

  [plugins.inputs.policies]
    childSrc = "https://www.youtube.com/embed/ https://www.youtube-nocookie.com/ https://player.vimeo.com/video/"
    connectSrc = "'self' https://plausible.io/api/event https://res.cloudinary.com"
    defaultSrc = "'self'"
    fontSrc = "'self'"
    frameSrc = "https://www.youtube.com/embed/ https://www.youtube-nocookie.com/ https://player.vimeo.com/video/"
    imgSrc = "'self' https://res.cloudinary.com/jackdbd/image/upload/"
    manifestSrc = "'self'"
    mediaSrc = "'none'"
    objectSrc = "'none'"
    scriptSrc = "'unsafe-inline' 'self'"
    scriptSrcAttr = "'none'"
    scriptSrcElem = "'self' https://plausible.io/js/plausible.js"
    styleSrc = "'self'"
    styleSrcAttr = "'self' 'unsafe-inline'"
    styleSrcElem = "'self' 'unsafe-inline'"
    workerSrc = "'self'"

# ---------------------------------------------------------------------------- #
# Deploy contexts                                                              #
# ---------------------------------------------------------------------------- #

[context.production]
  command = "npm run build"
  environment = { NODE_VERSION = "17.9.0" }

[context.deploy-preview]
  command = "npm run build"
  environment = { NODE_VERSION = "17.9.0" }

# ---------------------------------------------------------------------------- #
# Headers (don't use the _headers file. I prefer keeping everything here)      #
# ---------------------------------------------------------------------------- #

# Most of the time, we do NOT want to set the cache-control header for a site
# hosted on Netlify. Here is why:
# https://www.netlify.com/blog/2017/02/23/better-living-through-caching/

# Be sure to never store the service worker in any cache (no-store), and clear
# any existing cache responses (max-age=0)
# As far as I understand, the sw.js file is invalidated in the HTTP cache every
# 24 hours, so no-store,max-age=0 is probably overkill. Since sw.js is a tiny
# file, I think it's better to err on the side of caution.
# https://chromium.googlesource.com/chromium/src/+/master/docs/security/service-worker-security-faq.md#do-service-workers-live-forever
[[headers]]
  for = "/sw.js"
  [headers.values]
    cache-control = "no-store,max-age=0"

# Permissions-Policy is only partially supported in Chrome
# https://caniuse.com/?search=Permissions-Policy

# HSTS preload: READ THIS CAREFULLY!
# https://docs.netlify.com/domains-https/https-ssl/#hsts-preload
# https://hstspreload.org/#deployment-recommendations
# Check HSTS preload status here:
# https://hstspreload.org/

[[headers]]
  for = "*"
  [headers.values]
    NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'
    Permissions-Policy = "geolocation=(), microphone=()"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

# ---------------------------------------------------------------------------- #
# Redirects (don't use the _redirects file. I prefer keeping everything here)  #
# ---------------------------------------------------------------------------- #

[[redirects]]
  from = "/a-simple-git-hook-for-your-python-projects"
  to = "/posts/a-simple-git-hook-for-your-python-projects"

[[redirects]]
  from = "/adapter-pattern-in-python"
  to = "/posts/adapter-pattern-in-python"

[[redirects]]
  from = "/better-git-commits"
  to = "/posts/better-git-commits"

[[redirects]]
  from = "/bridge-pattern-in-python"
  to = "/posts/bridge-pattern-in-python"

[[redirects]]
  from = "/facade-pattern-in-python"
  to = "/posts/facade-pattern-in-python"

[[redirects]]
  from = "/factory-method-and-abstract-factory-in-python"
  to = "/posts/factory-method-and-abstract-factory-in-python"

[[redirects]]
  from = "/how-to-import-d3-plugins-with-webpack"
  to = "/posts/how-to-import-d3-plugins-with-webpack"

[[redirects]]
  from = "/my-personal-git-memo"
  to = "/posts/my-personal-git-memo"

[[redirects]]
  from = "/mvc-pattern-in-python-dataset"
  to = "/posts/mvc-pattern-in-python-dataset"

[[redirects]]
  from = "/mvc-pattern-in-python-introduction-and-basicmodel"
  to = "/posts/mvc-pattern-in-python-introduction-and-basicmodel"

[[redirects]]
  from = "/mvc-pattern-in-python-sqlite"
  to = "/posts/mvc-pattern-in-python-sqlite"

[[redirects]]
  from = "/reactive-dashboards-with-plotly-dash"
  to = "/posts/reactive-dashboards-with-plotly-dash"

[[redirects]]
  from = "/reading-large-excel-files-with-pandas"
  to = "/posts/reading-large-excel-files-with-pandas"

[[redirects]]
  from = "/squashing-git-commits"
  to = "/posts/squashing-git-commits"

[[redirects]]
  from = "/strategy-pattern-in-python"
  to = "/posts/strategy-pattern-in-python"

[[redirects]]
  from = "/template-method-pattern-in-python"
  to = "/posts/template-method-pattern-in-python"

[[redirects]]
  from = "/threejs-project-starter-for-es6-and-webpack-2"
  to = "/posts/threejs-project-starter-for-es6-and-webpack-2"

[[redirects]]
  from = "/visualize-earthquakes-with-plotly-dash"
  to = "/posts/visualize-earthquakes-with-plotly-dash"

[[redirects]]
  from = "*"
  to = "/404"
  status = 404
