[build]
  command = "npm run build"
  functions = "src/functions"
  publish = "_site"

[[plugins]]
package = "netlify-plugin-a11y"
  [plugins.inputs]
  checkPaths = [
    '/',
    '/blog/',
    '/projects/',
    '/about/',
    '/contact/',
  ]

[[plugins]]
package = "netlify-plugin-debug-cache"

[[plugins]]
package = "netlify-plugin-html-validate"
  [plugins.inputs]
    ext = "html"
    config = ".htmlvalidate.json"

[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "geolocation=(), microphone=(), vibrate=()"
    Referrer-Policy = "no-referrer"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"

# Include Content-Security-Policy header only for HTML resources. It doesn't
# make sense to include CSP for non-HTML resources, it would just be header bloat.
# https://webhint.io/docs/user-guide/hints/hint-no-html-only-headers/
# font-src: allow only fonts hosted on this origin or on Google Fonts
# frame-src: allow iframes only from YouTube and Vimeo
# img-src: allow only images hosted on my Cloudinary media library
[[headers]]
  for = "*.html"
  [headers.values]
  Content-Security-Policy = '''
    base-uri 'self';
    connect-src 'self';
    default-src 'self';
    font-src 'self' fonts.gstatic.com;
    form-action 'self';
    frame-ancestors 'none';
    frame-src https://www.youtube.com/embed/ https://player.vimeo.com/video/;
    img-src 'self' https://res.cloudinary.com/jackdbd/image/upload/;
    manifest-src 'self';
    media-src 'self' https://res.cloudinary.com/jackdbd/;
    object-src 'none';
    prefetch-src 'self';
    report-uri https://giacomodebidda.report-uri.com;
    script-src 'self' 'unsafe-inline';
    style-src 'self' 'unsafe-inline' fonts.googleapis.com fonts.gstatic.com https://unpkg.com/prismjs@1.20.0/themes/prism-okaidia.css;
    upgrade-insecure-requests'''
  X-XSS-Protection = "1; mode=block"

# TODO: Add Strict-Transport-Security header, eventually. READ THIS FIRST!
# https://docs.netlify.com/domains-https/https-ssl/#hsts-preload

[[redirects]]
  from = "*"
  to = "/404"
  status = 404