[build]
  command = "npm run build"
  functions = "src/functions"
  publish = "_site"

# ---------------------------------------------------------------------------- #
# Build plugins                                                                #
# ---------------------------------------------------------------------------- #

[[plugins]]
package = "netlify-plugin-a11y"
  [plugins.inputs]
  checkPaths = [
    '/',
    '/about/',
    '/blog/',
    '/contact/',
    '/projects/',
  ]

[[plugins]]
package = "netlify-plugin-debug-cache"

[[plugins]]
package = "netlify-plugin-html-validate"
  [plugins.inputs]
  ext = "html"
  config = ".htmlvalidate.json"

[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

# ---------------------------------------------------------------------------- #
# Cache headers                                                                #
# ---------------------------------------------------------------------------- #

# Most of the time, we do NOT want to set the cache-control header for a site
# hosted on Netlify. Here is why:
# https://www.netlify.com/blog/2017/02/23/better-living-through-caching/

# Be sure to never store the service worker in any cache (no-store), and clear
# any existing cache responses (max-age=0)
# As far as I understand, the sw.js file is invalidated in the HTTP cache every
# 24 hours, so no-store,max-age=0 is probably overkill. Since sw.js is a tiny
# file, I think it's better to err on the side of caution.
# https://chromium.googlesource.com/chromium/src/+/master/docs/security/service-worker-security-faq.md#do-service-workers-live-forever
[[headers]]
  for = "/sw.js"
  [headers.values]
    cache-control = "no-store,max-age=0"

# ---------------------------------------------------------------------------- #
# Security headers                                                             #
# ---------------------------------------------------------------------------- #

# Permissions-Policy is only partially supported in Chrome
# https://caniuse.com/?search=Permissions-Policy

# HSTS preload: READ THIS CAREFULLY!
# https://docs.netlify.com/domains-https/https-ssl/#hsts-preload
# https://hstspreload.org/#deployment-recommendations
# Check HSTS preload status here:
# https://hstspreload.org/

[[headers]]
  for = "*"
  [headers.values]
    NEL = '{"report_to":"default","max_age":31536000,"include_subdomains":true}'
    Permissions-Policy = "geolocation=(), microphone=()"
    Referrer-Policy = "no-referrer, strict-origin-when-cross-origin"
    Report-To = '''
    {
      "group": "default",
      "max_age": 31536000,
      "endpoints": [
        {"url": "https://giacomodebidda.report-uri.com/a/d/g"}
      ],
      "include_subdomains":true
    }
    '''
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# ---------------------------------------------------------------------------- #
# Content-Security-Policy (it's a security header)                             #
# The CSP for this website is generated automatically at build time.           #
# See prebuild.js                                                              #
# ---------------------------------------------------------------------------- #

# The Content-Security-Policy header should only be sent for HTML resources, but
# if I use for = "*.html" Netlify does not seem to send it every time (should I
# redirect DOMAIN/blog to DOMAIN/blog/index.html ?)
# https://webhint.io/docs/user-guide/hints/hint-no-html-only-headers/

[[headers]]
  for = "*"
  [headers.values]
    Content-Security-Policy = "base-uri 'self'; connect-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com https://res.cloudinary.com; default-src 'self'; font-src 'self' https://fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src https://www.youtube.com/embed/ https://player.vimeo.com/video/; img-src 'self' https://res.cloudinary.com/jackdbd/image/upload/; manifest-src 'self'; media-src 'self' https://res.cloudinary.com/jackdbd/image/upload/; object-src 'none'; report-to default; report-uri 'https://giacomodebidda.report-uri.com'; script-src 'self'; script-src-attr 'self' 'unsafe-inline'; script-src-elem 'self' 'sha256-edf371eee7349b74fb39dc0cf482445334c9e776b6fc8b0064d42be584a632b7' 'sha256-18ee7700c399211fd223101068e0521c970b8c5d15537576bcaee3f5437f9306'; style-src 'self' 'sha256-69ce753f5fb8cf39c6c09e90baa98b4673fad787a206b947256b8ea1bc69539d' https://fonts.googleapis.com https://unpkg.com/prismjs@1.20.0/themes/prism-okaidia.css; upgrade-insecure-requests; worker-src 'self'"

# ---------------------------------------------------------------------------- #
# Redirects                                                                    #
# ---------------------------------------------------------------------------- #

[[redirects]]
  from = "*"
  to = "/404"
  status = 404
