// THIS FILE WAS AUTOGENERATED - DO NOT MODIFY!
module.exports = {
  // The variables set here will be accessible both to templates, and to
  // 11ty transforms, shortcodes, filters, and collections.
  domain: process.env.DOMAIN,
  environment: process.env.ELEVENTY_ENV
}
