name: 'Ask HN Freelancer? Seeking Freelancer? (by whoishiring)'

on:
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # https://crontab.guru/
    - cron:  '45 15 5 * *'
  workflow_dispatch:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
    # You can trigger this workflow manually using the GitHub CLI:
    # gh workflow run "Ask HN Freelancer? Seeking Freelancer? (by whoishiring)" --ref branch-name

jobs:
  ask-hn-to-telegram:
    name: Post on Ask HN Freelancer? Seeking Freelancer?
    runs-on: ubuntu-latest
    
    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v4

      - name: 🖥️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current

      - name: Query Hacker News
        run: |
          delimiter=$(openssl rand -hex 8)
          echo "HN_JSON<<$delimiter" >> $GITHUB_ENV
          node scripts/hacker-news/whoishiring-item-id.cjs >> $GITHUB_ENV
          echo "$delimiter" >> $GITHUB_ENV

      - name: 💬 Notify Telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ fromJSON(secrets.TELEGRAM).chat_id }}
          token: ${{ fromJSON(secrets.TELEGRAM).token }}
          format: html
          disable_web_page_preview: true
          message: |
            <b>🤖 Ask HN Freelancer</b>

            <i>About to post ad to:</i>
            <a href="https://news.ycombinator.com/item?id=${{ fromJSON(env.HN_JSON).item_id }}">${{ fromJSON(env.HN_JSON).title }}</a>

            <i>Posted by ${{ fromJSON(env.HN_JSON).username }} in ${{ fromJSON(env.HN_JSON).date }}</i>

      - name: Read ad for Ask HN Freelancer
        run: |
          delimiter=$(openssl rand -hex 8)
          echo "HN_AD<<$delimiter" >> $GITHUB_ENV
          cat assets/ads/ask-hn-freelancer.txt >> $GITHUB_ENV
          echo "$delimiter" >> $GITHUB_ENV

      # Playwright complains if project dependencies are not installed
      - run: npm ci

      - name: Install Playwright and all browsers
        # https://github.com/microsoft/playwright-github-action#playwright-cli-with-github-actions-ci
        run: npx playwright install --with-deps

      # TODO: run playwright script to post the ad to HN
      # https://github.com/microsoft/playwright-github-action#-use-the-playwright-cli
      - name: Post my ad on HN using Playwright
        env:
          DEBUG: hn:*,script:*
          HACKER_NEWS: ${{ secrets.HACKER_NEWS }}
          NODE_DEBUG: hn:*,script:*
        run: |
          delimiter=$(openssl rand -hex 8)
          echo "RESULT_STRING<<$delimiter" >> $GITHUB_ENV
          node scripts/hacker-news/post-ad-on-ask-hn-seeking-freelancer.mjs ${{ fromJSON(env.HN_JSON).item_id }} >> $GITHUB_ENV
          echo "$delimiter" >> $GITHUB_ENV

      - name: 💬 Notify Telegram of my ad
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ fromJSON(secrets.TELEGRAM).chat_id }}
          token: ${{ fromJSON(secrets.TELEGRAM).token }}
          format: html
          disable_web_page_preview: true
          message: |
            <b>🤖 Ask HN Freelancer ad posting result</b>

            <pre>${{ env.RESULT_STRING }}</pre>
