name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    name: Build website, run tests, deploy to Netlify
    runs-on: ubuntu-latest
    env:
      NODE_LATEST_LTS: 14.17.0 # keep this up to date!
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ env.NODE_LATEST_LTS }}
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_LATEST_LTS }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build website
        run: npm run build
  wpt:
    name: Audit website with WebPageTest API
    needs: [build-and-test]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wait for a successfull Deploy Preview on Netlify
        # https://github.com/JakePartusch/wait-for-netlify-action
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: ${{ secrets.SITE_NAME }}
          max_timeout: 60
      - name: Audit pages with WebPageTest (home/contact, mobile)
        # https://github.com/WPO-Foundation/webpagetest-github-action
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label: 'home-contact-mobile'
          urls: |
            ${{ steps.netlify.outputs.url }}/
            ${{ steps.netlify.outputs.url }}/contact/
          budget: 'wpt-budget.json'
          wptOptions: 'wpt-options-mobile.json'
      - name: Audit pages with WebPageTest (home/contact, desktop)
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label: 'home-contact-desktop'
          urls: |
            ${{ steps.netlify.outputs.url }}/
            ${{ steps.netlify.outputs.url }}/contact/
          budget: 'wpt-budget.json'
          wptOptions: 'wpt-options-desktop.json'
      - name: Audit page with WebPageTest (article, desktop)
        uses: WPO-Foundation/webpagetest-github-action@main
        env:
          ARTICLE_SLUG: 12-years-of-fires-in-sardinia
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label: 'article-desktop'
          urls: |
            ${{ steps.netlify.outputs.url }}/posts/${{ env.ARTICLE_SLUG }}
          budget: 'wpt-budget-article-desktop.json'
          wptOptions: 'wpt-options-desktop.json'
  audit:
    name: Audit website with Lighthouse CI
    needs: [build-and-test]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wait for a successfull Deploy Preview on Netlify
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: ${{ secrets.SITE_NAME }}
          max_timeout: 60
      - name: Audit contact page with Lighthouse CI (mobile)
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}/contact/
          configPath: lighthouse/lighthouserc-contact-mobile.js
          temporaryPublicStorage: true
          uploadArtifacts: true
      - name: Audit contact page with Lighthouse CI (desktop)
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}/contact/
          configPath: lighthouse/lighthouserc-contact-desktop.js
          temporaryPublicStorage: true
          uploadArtifacts: true
      - name: Audit home, blog, project page with Lighthouse CI (desktop)
        uses: treosh/lighthouse-ci-action@v7
        env:
          ARTICLE_SLUG: 12-years-of-fires-in-sardinia
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}/
            ${{ steps.netlify.outputs.url }}/blog/
            ${{ steps.netlify.outputs.url }}/posts/${{ env.ARTICLE_SLUG }}
            ${{ steps.netlify.outputs.url }}/projects/
          configPath: lighthouse/lighthouserc-all-desktop.js
          temporaryPublicStorage: true
          uploadArtifacts: true