name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    name: 🔧 Build website and run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['16.16.0']
    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v3
      - name: 🖥️ Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - name: 🛡️ Audit security
        continue-on-error: true
        if: ${{ matrix.os }} == 'ubuntu-latest'
        run: npm audit --audit-level=moderate
      - name: 🔍 Test website
        run: npm run test
      - name: 🔧 Build website
        env:
          CLOUDINARY: ${{ secrets.CLOUDINARY }}
          DEBUG: Eleventy:cmd,Eleventy:ErrorHandler,Eleventy:UserConfig
          DOMAIN: ${{ secrets.DOMAIN }}
          ELEVENTY_ENV: production
          NODE_ENV: development
          PLAUSIBLE: ${{ secrets.PLAUSIBLE }}
          TELEGRAM: ${{ secrets.TELEGRAM }}
          WEBPAGETEST: ${{ secrets.WEBPAGETEST }}
        run: npm run build

  # I am commenting this out because at the moment I don't have a valid API key for WebPageTest
  # wpt:
  #   name: Audit website with WebPageTest API
  #   needs: [build-and-test]
  #   if: ${{ github.event_name == 'pull_request' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 🛎️ Checkout repo
  #       uses: actions/checkout@v3
  #     - name: Wait for a successfull Deploy Preview on Netlify
  #       # https://github.com/JakePartusch/wait-for-netlify-action
  #       uses: jakepartusch/wait-for-netlify-action@v1
  #       id: netlify
  #       with:
  #         site_name: ${{ secrets.SITE_NAME }}
  #         max_timeout: 60
  #     - name: Audit pages with WebPageTest (home/contact, mobile)
  #       # https://github.com/WPO-Foundation/webpagetest-github-action
  #       uses: WPO-Foundation/webpagetest-github-action@v1.1.2
  #       with:
  #         apiKey: ${{ secrets.WPT_API_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         label: 'home-contact-mobile'
  #         urls: |
  #           ${{ steps.netlify.outputs.url }}/
  #           ${{ steps.netlify.outputs.url }}/contact/
  #         budget: 'wpt-budget.json'
  #         wptOptions: 'wpt-options-mobile.json'
  #     - name: Audit pages with WebPageTest (home/contact, desktop)
  #       uses: WPO-Foundation/webpagetest-github-action@v1.1.2
  #       with:
  #         apiKey: ${{ secrets.WPT_API_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         label: 'home-contact-desktop'
  #         urls: |
  #           ${{ steps.netlify.outputs.url }}/
  #           ${{ steps.netlify.outputs.url }}/contact/
  #         budget: 'wpt-budget.json'
  #         wptOptions: 'wpt-options-desktop.json'
  #     - name: Audit page with WebPageTest (article, desktop)
  #       uses: WPO-Foundation/webpagetest-github-action@v1.1.2
  #       env:
  #         ARTICLE_SLUG: 12-years-of-fires-in-sardinia
  #       with:
  #         apiKey: ${{ secrets.WPT_API_KEY }}
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         label: 'article-desktop'
  #         urls: |
  #           ${{ steps.netlify.outputs.url }}/posts/${{ env.ARTICLE_SLUG }}
  #         budget: 'wpt-budget-article-desktop.json'
  #         wptOptions: 'wpt-options-desktop.json'

  # TOOD: wait for successful Deploy Preview on Cloudflare Pages
  # audit:
  #   name: Audit website with Lighthouse CI
  #   needs: [build-and-test]
  #   if: ${{ github.event_name == 'pull_request' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Wait for a successful Deploy Preview on Netlify
  #       uses: jakepartusch/wait-for-netlify-action@v1
  #       id: netlify
  #       with:
  #         site_name: ${{ secrets.SITE_NAME }}
  #         max_timeout: 60

  #     - name: 🌐 Notify Telegram chat about Netlify deployment
  #       uses: appleboy/telegram-action@v0.1.1
  #       with:
  #         to: ${{ fromJSON(secrets.TELEGRAM).chat_id }}
  #         token: ${{ fromJSON(secrets.TELEGRAM).token }}
  #         format: html
  #         disable_web_page_preview: true
  #         # https://core.telegram.org/bots/api#formatting-options
  #         message: |
  #           <b>🌐 New deploy preview on Netlify</b>

  #           The website <code>${{ secrets.SITE_NAME }}</code> is <b>live</b> at:
  #           <a href="${{ steps.netlify.outputs.url }}">${{ steps.netlify.outputs.url }}</a>

  #           Repository: <a href="https://github.com/${{ github.repository }}/">${{ github.repository }}</a>

  #           <a href="https://github.com/${{ github.repository }}/commit/${{github.sha}}">Changes</a> in commit <code>${{github.sha}}</code>

  #     - name: Audit contact page with Lighthouse CI (mobile)
  #       uses: treosh/lighthouse-ci-action@v7
  #       with:
  #         urls: |
  #           ${{ steps.netlify.outputs.url }}/contact/
  #         configPath: lighthouse/lighthouserc-contact-mobile.js
  #         temporaryPublicStorage: true
  #         uploadArtifacts: true
        
  #     - name: Audit contact page with Lighthouse CI (desktop)
  #       uses: treosh/lighthouse-ci-action@v7
  #       with:
  #         urls: |
  #           ${{ steps.netlify.outputs.url }}/contact/
  #         configPath: lighthouse/lighthouserc-contact-desktop.js
  #         temporaryPublicStorage: true
  #         uploadArtifacts: true
        
      # - name: Audit home, blog, project page with Lighthouse CI (desktop)
      #   uses: treosh/lighthouse-ci-action@v7
      #   env:
      #     ARTICLE_SLUG: 12-years-of-fires-in-sardinia
      #   with:
      #     urls: |
      #       ${{ steps.netlify.outputs.url }}/
      #       ${{ steps.netlify.outputs.url }}/blog/
      #       ${{ steps.netlify.outputs.url }}/projects/
      #       ${{ steps.netlify.outputs.url }}/posts/${{ env.ARTICLE_SLUG }}
      #     configPath: lighthouse/lighthouserc-all-desktop.js
      #     temporaryPublicStorage: true
      #     uploadArtifacts: true