name: Run Lighthouse CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Lighthouse CI and Lighthouse plugins
        run: npm install @lhci/cli lighthouse-plugin-field-performance
      - name: run Lighthouse CI
        run: npm run lhci
