name: Build, deploy, audit
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build website, run tests, deploy to Netlify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build website
        run: npm run build
  audit:
    name: Audit deployed website with Lighthouse CI
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Wait for a successfull Deploy Preview on Netlify
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'epic-benz-a3f006'
          max_timeout: 60
      - name: Audit contact page with Lighthouse CI (mobile)
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}/contact/
          configPath: lighthouse/lighthouserc-contact-mobile.js
          uploadArtifacts: true
          temporaryPublicStorage: true
      - name: Audit contact page with Lighthouse CI (desktop)
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}/contact/
          configPath: lighthouse/lighthouserc-contact-desktop.js
          uploadArtifacts: true
          temporaryPublicStorage: true
      - name: Audit home, blog, project page with Lighthouse CI (desktop)
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            ${{ steps.netlify.outputs.url }}/
            ${{ steps.netlify.outputs.url }}/blog/
            ${{ steps.netlify.outputs.url }}/projects/
          configPath: lighthouse/lighthouserc-all-desktop.js
          uploadArtifacts: true
          temporaryPublicStorage: true