name: 'Pull Content'

on:
  repository_dispatch:
    types:
      # This event should match the event_type sent by this other GitHub Workflow:
      # https://github.com/jackdbd/giacomodebidda-content/blob/41a6eeb943c844825d3073e7f04c5e9f9aaa2b09/.github/workflows/ci.yaml#L18
      # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch
      - pull-content

jobs:
  pull-content-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v4

      - name: 🖥️ Set up Git
        run: |
          git config user.name "Giacomo Debidda"
          git config user.email "giacomo@giacomodebidda.com"

      - name: Install git-subrepo
        run: |
          git clone https://github.com/ingydotnet/git-subrepo.git /tmp/git-subrepo
          sudo ln -s /tmp/git-subrepo/lib/git-subrepo /usr/local/bin/git-subrepo
          # verify the installation
          echo "git subrepo version $(git subrepo --version)"

      - name: ⬇️ Pull content using git-subrepo
        env:
          GIT_ASKPASS: /bin/echo
          GIT_PASSWORD: ${{ secrets.TOKEN_FOR_PULL_CONTENT_EVENT }}
        run: |
          echo "subrepo status BEFORE pulling content"
          git subrepo status
          # git-subrepo pull https://$GITHUB_ACTOR:$GIT_PASSWORD@github.com/jackdbd/giacomodebidda-content.git content --force
          git subrepo pull content --force
          # verify that the content has been pulled
          ls -1 content/bookmarks/
          ls -1 content/likes/
          ls -1 content/notes/
          echo "subrepo status AFTER pulling content"
          git subrepo status
          # git add .
          # git commit -m "Update content subrepo"
          # git push origin HEAD
