name: 'Pull Content'

on:
  repository_dispatch:
    types:
      # This event should match the event_type sent by this other GitHub Workflow:
      # https://github.com/jackdbd/giacomodebidda-content/blob/41a6eeb943c844825d3073e7f04c5e9f9aaa2b09/.github/workflows/ci.yaml#L18
      # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#repository_dispatch
      - pull-content

jobs:
  pull-content-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v4

      - name: 🖥️ Install git-subrepo
        run: |
          git clone https://github.com/ingydotnet/git-subrepo.git /tmp/git-subrepo
          sudo ln -s /tmp/git-subrepo/lib/git-subrepo /usr/local/bin/git-subrepo
          # verify the installation
          echo "git subrepo version $(git subrepo --version)"

      - name: ⚙️ Configure Git and override subrepo remote
        # During the execution of git subrepo pull, the value in subrepo.content.url
        # is used instead of the remote specified in the content/.gitrepo file.
        env:
          GIT_ASKPASS: /bin/echo
          GIT_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Giacomo Debidda"
          git config user.email "giacomo@giacomodebidda.com"
          git config --global credential.helper store
          echo "https://$GITHUB_ACTOR:$GIT_PASSWORD@github.com" > ~/.git-credentials
          # git config subrepo.content.url https://github.com/jackdbd/giacomodebidda-content.git

      - name: ⬇️ Pull content using git-subrepo and commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "subrepo status BEFORE pulling content"
          git subrepo status
          git subrepo pull content --force
          # verify that the content has been pulled
          ls -1 content/bookmarks/
          ls -1 content/likes/
          ls -1 content/notes/
          echo "subrepo status AFTER pulling content"
          git subrepo status

      - name: Push to remote
        run: git push
