name: 'Reddit search'

on:
  schedule:
    - cron:  '45 23 * * 1'
  workflow_dispatch:
    # You can trigger this workflow manually using the GitHub CLI:
    # gh workflow run "Reddit search" --ref branch-name

jobs:
  post-on-reddit-and-notify-telegram:
    name: Post on Reddit and notify Telegram
    runs-on: ubuntu-latest
    
    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v4

      - name: 🖥️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current

      - run: npm ci

      - name: 🤖 Search Reddit
        env:
          REDDIT: ${{ secrets.REDDIT }}
        run: |
          delimiter=$(openssl rand -hex 8)
          echo "TELEGRAM_MESSAGE<<$delimiter" >> $GITHUB_ENV
          node scripts/reddit/search.cjs >> $GITHUB_ENV
          echo "$delimiter" >> $GITHUB_ENV

      - name: 💬 Notify Telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ fromJSON(secrets.TELEGRAM).chat_id }}
          token: ${{ fromJSON(secrets.TELEGRAM).token }}
          format: html
          disable_web_page_preview: true
          message: ${{ env.TELEGRAM_MESSAGE }}
