name: 'Reddit search'

on:
  schedule:
    - cron: '45 23 * * 1' # UTC time
  workflow_dispatch:
    # You can trigger this workflow manually using the GitHub CLI:
    # gh workflow run "Reddit search" --ref branch-name

jobs:
  search-reddit-and-notify-telegram:
    name: Search Reddit and notify Telegram
    runs-on: ubuntu-latest
    
    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v4

      - name: 🖥️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current

      - run: npm ci

      - name: 🤖 Search Reddit
        env:
          DEBUG: reddit:*,script:*
          NODE_DEBUG: reddit:*,script:*
          REDDIT: ${{ secrets.REDDIT }}
          TELEGRAM: ${{ secrets.TELEGRAM }}
        run: |
          delimiter=$(openssl rand -hex 8)
          echo "TELEGRAM_MESSAGE<<$delimiter" >> $GITHUB_ENV
          node scripts/reddit/search.mjs >> $GITHUB_ENV
          echo "$delimiter" >> $GITHUB_ENV

      - name: 💬 Notify Telegram
        uses: appleboy/telegram-action@v1
        with:
          to: ${{ fromJSON(secrets.TELEGRAM).chat_id }}
          token: ${{ fromJSON(secrets.TELEGRAM).token }}
          format: html
          disable_web_page_preview: true
          message: ${{ env.TELEGRAM_MESSAGE }}
