name: 'Reddit links to Telegram'

on:
  schedule:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # https://crontab.guru/
    - cron:  '55 9 * * 1'
  workflow_dispatch:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
    # You can trigger this workflow manually using the GitHub CLI:
    # gh workflow run "Reddit links to Telegram" --ref branch-name

jobs:
  steampipe-reddit-telegram:
    name: Reddit links to Telegram
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v4

      - name: 🖥️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current

      - name: Setup Steampipe and its plugins
        # https://github.com/marketplace/actions/setup-steampipe
        uses: turbot/steampipe-action-setup@v1
    
        with:
          steampipe-version: latest
          # https://hub.steampipe.io/plugins/turbot/hackernews#configuration
          # https://hub.steampipe.io/plugins/turbot/reddit#configuration
          plugin-connections: |
            connection "hackernews" {
              plugin = "hackernews"
              max_items = 5000
            }

            connection "reddit" {
              plugin = "reddit"
              client_id = "${{ fromJSON(secrets.REDDIT).client_id }}"
              client_secret = "${{ fromJSON(secrets.REDDIT).client_secret }}"
              username = "${{ fromJSON(secrets.REDDIT).username }}"
              password = "${{ fromJSON(secrets.REDDIT).password }}"
            }

      - name: Query Reddit for React jobs
        run: |
          delimiter=$(openssl rand -hex 8)
          echo "REDDIT_RESULTS_AS_JSON<<$delimiter" >> $GITHUB_ENV
          steampipe query assets/steampipe-queries/react-jobs-on-jobbit-subreddit.sql --output json >> $GITHUB_ENV
          echo "$delimiter" >> $GITHUB_ENV

      - name: Convert array to string (React)
        run: |
          delimiter=$(openssl rand -hex 8)
          echo "REACT_JOBS_LINKS<<$delimiter" >> $GITHUB_ENV
          node scripts/reddit-array-to-telegram-links.mjs >> $GITHUB_ENV
          echo "$delimiter" >> $GITHUB_ENV

      - name: 💬 Send React jobs to Telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ fromJSON(secrets.TELEGRAM).chat_id }}
          token: ${{ fromJSON(secrets.TELEGRAM).token }}
          format: html
          disable_web_page_preview: true
          message: |
            <b>🤖 React jobs posted in r/jobbit</b>

            ${{ env.REACT_JOBS_LINKS }}
