name: 'Stripe Promotion Codes'

on:
  schedule:
    # https://crontab.guru/
    - cron: '45 13 * * 4' # UTC time
  workflow_dispatch:
    # You can trigger this workflow manually using the GitHub CLI:
    # gh workflow run "Stripe Promotion Codes"

jobs:
  renew-stripe-promo-codes-and-notify-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v4

      - name: 🖥️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current

      - run: npm ci

      - name: Renew Stripe promotion codes
        env:
          DEBUG: script:*,stripe:*
          STRIPE_LIVE: ${{ secrets.STRIPE_LIVE }}
          STRIPE_TEST: ${{ secrets.STRIPE_TEST }}
        run: |
          delimiter=$(openssl rand -hex 8)
          echo "TELEGRAM_MESSAGE<<$delimiter" >> $GITHUB_ENV
          npx tsm scripts/stripe/renew-promotion-codes.ts -e live >> $GITHUB_ENV
          echo "$delimiter" >> $GITHUB_ENV

      - name: 💬 Notify Telegram of Promotion Codes
        uses: appleboy/telegram-action@v1
        with:
          to: ${{ fromJSON(secrets.TELEGRAM).chat_id }}
          token: ${{ fromJSON(secrets.TELEGRAM).token }}
          format: html
          disable_web_page_preview: true
          message: ${{ env.TELEGRAM_MESSAGE }}
  
      - name: List Stripe Coupons
        env:
          DEBUG: script:*,stripe:*
          STRIPE_LIVE: ${{ secrets.STRIPE_LIVE }}
          STRIPE_TEST: ${{ secrets.STRIPE_TEST }}
        run: |
          delimiter=$(openssl rand -hex 8)
          echo "TELEGRAM_MESSAGE<<$delimiter" >> $GITHUB_ENV
          npx tsm scripts/stripe/list-coupons-and-promotion-codes.ts -e live >> $GITHUB_ENV
          echo "$delimiter" >> $GITHUB_ENV

      - name: 💬 Notify Telegram of Coupons
        uses: appleboy/telegram-action@v1
        with:
          to: ${{ fromJSON(secrets.TELEGRAM).chat_id }}
          token: ${{ fromJSON(secrets.TELEGRAM).token }}
          format: html
          disable_web_page_preview: true
          message: ${{ env.TELEGRAM_MESSAGE }}
