name: WebPageTest audit
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#schedule
  schedule:
    # https://crontab.guru/every-12-hours
    - cron:  '0 */12 * * *'
  # allow to trigger this workflow manually
  # https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event--parameters
  workflow_dispatch:
jobs:
  audit:
    name: Audit website with the WebPageTest API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Audit / and /contact with WebPageTest (mobile)
        # https://github.com/WPO-Foundation/webpagetest-github-action
        # All WebPageTest options are set via the wptOptions input
        uses: WPO-Foundation/webpagetest-github-action@main
        # unfortunately this action has no outputs, so it's pointless to assign
        # an `id` to this step to access `steps.wpt_home_mobile.outputs` later
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label: 'home-contact-mobile'
          urls: |
            ${{ secrets.SITE_NAME }}/
            ${{ secrets.SITE_NAME }}/contact/
          wptOptions: 'wpt-options-mobile.json'
          budget: 'wpt-budget.json'
      - name: Audit / and /contact with WebPageTest (desktop)
        uses: WPO-Foundation/webpagetest-github-action@main
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label: 'home-contact-desktop'
          urls: |
            ${{ secrets.SITE_NAME }}/
            ${{ secrets.SITE_NAME }}/contact/
          wptOptions: 'wpt-options-desktop.json'
          budget: 'wpt-budget.json'
      - name: Audit /posts/${{ env.ARTICLE_SLUG }} with WebPageTest (desktop)
        uses: WPO-Foundation/webpagetest-github-action@main
        env:
          ARTICLE_SLUG: 12-years-of-fires-in-sardinia
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label: 'article-desktop'
          urls: |
            ${{ secrets.SITE_NAME }}/posts/${{ env.ARTICLE_SLUG }}
          wptOptions: 'wpt-options-desktop.json'
          budget: 'wpt-budget-article-desktop.json'
      - name: Dump workflow dispatch
        env:
          WORKFLOW_DISPATCH: ${{ toJSON(github.event.workflow_dispatch) }}
        run: echo "$WORKFLOW_DISPATCH"
      - name: Notify Telegram of WebPageTest performace audit
        # https://github.com/appleboy/telegram-action
        # This is a container action, so it must run on Linux (it would fail if
        # `runs-on` is either `windows-latest` or `macOS-latest`)
        # https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#introduction
        uses: appleboy/telegram-action@master
        env:
          REPO_URL: ${{ github.event.repository.html_url }}
          WORKFLOW_URL: ${{ github.event.workflow_dispatch.html_url }}
          WORKFLOW_CREATED_AT: ${{ github.event.workflow_dispatch.created_at }}
          # HOME_MOBILE_OUTPUTS: ${{ toJSON(steps.wpt_home_mobile.outputs) }}
          # ARTICLE_DESKTOP_OUTPUTS: ${{ toJSON(steps.wpt_article_desktop.outputs) }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          # https://emojipedia.org/
          message: |
            🚀 WebPageTest audit report ready
            Repo: ${{ env.REPO_URL }}
            Workflow: ${{ env.WORKFLOW_URL }}
            Created at: ${{ env.WORKFLOW_CREATED_AT }}
            Workflow ID ${{ github.event.workflow_dispatch.workflow_id }}
