name: WebPageTest audit
on:
  # allow to trigger this workflow manually
  # https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event--parameters
  workflow_dispatch:
jobs:
  audit:
    name: Audit website with the WebPageTest API
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: 🛎️ Checkout repo
        uses: actions/checkout@v3
      - name: Audit / and /contact with WebPageTest (mobile)
        # https://github.com/WPO-Foundation/webpagetest-github-action
        # All WebPageTest options are set via the wptOptions input
        uses: WPO-Foundation/webpagetest-github-action@v1.1.2
        # unfortunately this action has no outputs, so it's pointless to assign
        # an `id` to this step to access `steps.wpt_home_mobile.outputs` later
        # id: wpt_home_mobile
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label: 'home-contact-mobile'
          urls: |
            ${{ secrets.SITE_NAME }}/
            ${{ secrets.SITE_NAME }}/contact/
          wptOptions: 'wpt-options-mobile.json'
          # budget: 'wpt-budget.json'
      - name: Audit / and /contact with WebPageTest (desktop)
        uses: WPO-Foundation/webpagetest-github-action@v1.1.2
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label: 'home-contact-desktop'
          urls: |
            ${{ secrets.SITE_NAME }}/
            ${{ secrets.SITE_NAME }}/contact/
          wptOptions: 'wpt-options-desktop.json'
          # budget: 'wpt-budget.json'
      - name: Audit /posts/${{ env.ARTICLE_SLUG }} with WebPageTest (desktop)
        uses: WPO-Foundation/webpagetest-github-action@v1.1.2
        env:
          ARTICLE_SLUG: 12-years-of-fires-in-sardinia
        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          label: 'article-desktop'
          urls: |
            ${{ secrets.SITE_NAME }}/posts/${{ env.ARTICLE_SLUG }}
          wptOptions: 'wpt-options-desktop.json'
          # budget: 'wpt-budget-article-desktop.json'
      - name: Notify Telegram of WebPageTest performace audit
        # https://github.com/appleboy/telegram-action
        # This is a container action, so it must run on Linux (it would fail if
        # `runs-on` is either `windows-latest` or `macOS-latest`)
        # https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#introduction
        uses: appleboy/telegram-action@v0.1.1
        env:
          REPO_URL: ${{ github.event.repository.html_url }}
          WORKFLOW_URL: https://github.com/jackdbd/personal-website/actions/workflows/wpt-audit.yml
          # HOME_MOBILE_RESULTS: ${{ steps.wpt_home_mobile.outputs.full_test_results }}
          # ARTICLE_DESKTOP_OUTPUTS: ${{ toJSON(steps.wpt_article_desktop.outputs) }}
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          # https://emojipedia.org/
          message: |
            🚀 WebPageTest audit report ready
            Repo: ${{ env.REPO_URL }}
            Workflow: ${{ env.WORKFLOW_URL }}
